#!/bin/bash
# Nginx serves the only public endpoint we have; without it, nothing
# works from the outside.
exec 0<&-
echo "$1" > /run/s6-linux-init-container-results/exitcode
exec /run/s6/basedir/bin/halt
