"""Tiny HTTP service that backs Jitsi local-recording upload + listing.

Runs inside the openhost-jitsi container alongside the four jitsi
services (web/prosody/jicofo/jvb), listens on 127.0.0.1:5060, and is
proxied to by nginx under /api/recordings/* and /<admin_token>/*.

Threat model
------------

Two classes of endpoint:

* ``/api/recordings/{init,<id>/chunk,<id>/finalize}`` — anonymous;
  anyone in a meeting can upload. The room name is a string the
  client provides and we store but don't trust.
* ``/_recordings/<admin_token>/*`` — admin endpoints, where
  ``<admin_token>`` is a 24-byte URL-safe random string (32
  base64url characters) generated on first boot and printed to the
  container logs. Possessing the token grants list / download /
  delete on every recording, indefinitely. There is no per-recording
  ACL — recordings live or die by whoever holds the admin URL.
  Treat the admin URL like a password.

  The ``/_recordings/`` prefix exists so the URL doesn't collide
  with Jitsi room names (Jitsi's room URLs are bare path segments
  like ``/randomwordname``; the underscore prefix can never be
  generated by the Jitsi UI's room-name generator).

Storage
-------

Files live under the directory passed via ``--rec-dir`` (the
``recordings-init.sh`` cont-init points it at
``$OPENHOST_APP_DATA_DIR/recordings``):

    <id>.webm   - the finished recording
    <id>.json   - {id, room, started_by, started_at, finished_at,
                   size_bytes, finalized}

While a recording is uploading, the file lives at ``<id>.webm.tmp``
and the JSON has ``finalized: false``. ``finalize`` swaps it to
``<id>.webm``. A startup sweep deletes any orphaned ``*.tmp`` files
and any JSON whose recording file is missing.

A total-size quota (``--max-bytes``, default 5 GiB) is enforced by
deleting the oldest finalized recordings AFTER a successful chunk
write. Pre-write eviction would let an attacker trigger eviction by
claiming a large Content-Length and disconnecting; we instead
fail-fast a chunk that couldn't possibly fit even with maximum
eviction, and only actually evict once we've received bytes.
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import os
import re
import secrets
import shutil
import sys
import threading
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

logger = logging.getLogger("openhost-jitsi-recordings")


# Default cap; override with --max-bytes (set via the run-script
# render in recordings-init.sh; no env var path).
DEFAULT_MAX_BYTES = 5 * 1024 * 1024 * 1024  # 5 GiB
DEFAULT_CHUNK_SIZE = 5 * 1024 * 1024  # 5 MiB

# Hard upper bound on a single chunk request. The JS shim sends 5 MiB
# chunks; we cap a bit above that to leave room for a future bump
# without rolling the wire format. Without this cap a malicious or
# buggy client can claim Content-Length: <huge> in one request and
# trigger preemptive eviction of every existing finalized recording
# before sending a single byte.
MAX_CHUNK_BYTES = 16 * 1024 * 1024  # 16 MiB

# Recording IDs are URL-safe random hex; we generate them ourselves and
# never trust client input.
ID_RE = re.compile(r"^[a-f0-9]{16}$")
ROOM_RE = re.compile(r"^[A-Za-z0-9._\- ]{1,128}$")

# Lock guarding state-file mutations and quota eviction.  All file IO
# inside this lock is local-disk-only and bounded; we don't hold it
# across the multi-megabyte chunk reads themselves.
_state_lock = threading.RLock()

# Per-recording locks serialize chunk writes for a single recording
# so concurrent POSTs for the same rec_id can't interleave bytes in
# the .webm.tmp file. The ``_state_lock`` guards mutations of this
# dict itself; the lock objects within it are then taken outside the
# global state lock so multiple recordings can stream concurrently.
_chunk_locks: dict[str, threading.Lock] = {}


def _chunk_lock_for(rec_id: str) -> threading.Lock:
    with _state_lock:
        lock = _chunk_locks.get(rec_id)
        if lock is None:
            lock = threading.Lock()
            _chunk_locks[rec_id] = lock
        return lock


def _drop_chunk_lock(rec_id: str) -> None:
    with _state_lock:
        _chunk_locks.pop(rec_id, None)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _meta_path(rec_dir: Path, rec_id: str) -> Path:
    return rec_dir / f"{rec_id}.json"


def _final_path(rec_dir: Path, rec_id: str) -> Path:
    return rec_dir / f"{rec_id}.webm"


def _tmp_path(rec_dir: Path, rec_id: str) -> Path:
    return rec_dir / f"{rec_id}.webm.tmp"


def _read_meta(rec_dir: Path, rec_id: str) -> dict[str, Any] | None:
    try:
        return json.loads(_meta_path(rec_dir, rec_id).read_text())
    except FileNotFoundError:
        return None
    except json.JSONDecodeError:
        logger.warning("Corrupt metadata for %s; ignoring", rec_id)
        return None
    except OSError as e:
        # Permissions / IO error reading the file. Log and treat as
        # "no such recording" so callers don't propagate raw
        # filesystem errors back to clients.
        logger.warning("Could not read metadata for %s: %s", rec_id, e)
        return None


def _write_meta(rec_dir: Path, rec_id: str, meta: dict[str, Any]) -> None:
    path = _meta_path(rec_dir, rec_id)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(meta, sort_keys=True))
    os.replace(tmp, path)


def _list_meta(rec_dir: Path) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for p in sorted(rec_dir.glob("*.json")):
        rec_id = p.stem
        if not ID_RE.fullmatch(rec_id):
            continue
        meta = _read_meta(rec_dir, rec_id)
        if meta is None:
            continue
        out.append(meta)
    out.sort(key=lambda m: m.get("started_at", ""), reverse=True)
    return out


def _disk_usage(rec_dir: Path) -> int:
    """Total bytes consumed by finalized recordings + in-flight tmp
    uploads. We count tmp files so a flood of unfinalized uploads
    can't bypass the quota.
    """
    total = 0
    for p in rec_dir.iterdir():
        if p.is_file():
            try:
                total += p.stat().st_size
            except OSError as e:
                logger.warning("Could not stat %s for quota accounting: %s", p.name, e)
    return total


def _evict_until_under_cap(rec_dir: Path, headroom_bytes: int, max_bytes: int) -> None:
    """Delete oldest finalized recordings until total + headroom <= cap.

    Tmp uploads-in-progress are NOT evicted (we don't know if more
    bytes are coming) but they ARE counted in the total — a flood of
    unfinalized uploads will refuse to evict any finalized recordings
    once finalized bytes alone are under the cap.
    """
    metas = sorted(_list_meta(rec_dir), key=lambda m: m.get("started_at", ""))
    total = _disk_usage(rec_dir)
    for meta in metas:
        if total + headroom_bytes <= max_bytes:
            return
        if not meta.get("finalized"):
            continue
        rec_id = meta["id"]
        size = int(meta.get("size_bytes", 0))
        # Delete the data file first; if that fails we keep the
        # metadata so the listing still shows the broken recording.
        # If only the metadata delete fails we still subtract from
        # ``total`` — the bytes are gone — and the next startup
        # sweep will reap the orphan json.
        try:
            _final_path(rec_dir, rec_id).unlink(missing_ok=True)
        except OSError as e:
            logger.warning("Eviction of %s data failed: %s", rec_id, e)
            continue
        try:
            _meta_path(rec_dir, rec_id).unlink(missing_ok=True)
        except OSError as e:
            logger.warning("Eviction of %s metadata failed (file already deleted): %s", rec_id, e)
        total -= size
        logger.info("Evicted %s (%d bytes) to make room", rec_id, size)


def _sweep_orphans(rec_dir: Path) -> None:
    """At startup: drop *.tmp / *.json.tmp files (interrupted writes),
    metadata for finalized recordings whose .webm is missing, and
    metadata for unfinalized recordings whose .webm.tmp is also gone
    (these can't ever be resumed and would otherwise stay visible
    forever as 'uploading').

    The .tmp sweep runs first, so the json sweep's existence check
    catches the cases where we just deleted the corresponding .tmp.
    """
    for pattern in ("*.webm.tmp", "*.json.tmp"):
        for p in rec_dir.glob(pattern):
            try:
                p.unlink()
                logger.info("Removed orphan %s", p.name)
            except OSError as e:
                logger.warning("Could not remove orphan %s: %s", p.name, e)
    for p in rec_dir.glob("*.json"):
        rec_id = p.stem
        if not ID_RE.fullmatch(rec_id):
            continue
        meta = _read_meta(rec_dir, rec_id)
        if meta is None:
            continue
        finalized = bool(meta.get("finalized"))
        has_final = _final_path(rec_dir, rec_id).exists()
        has_tmp = _tmp_path(rec_dir, rec_id).exists()
        if finalized and not has_final:
            stale_reason = "missing recording file"
        elif not finalized and not has_tmp:
            stale_reason = "no .webm.tmp; upload was interrupted and can't resume"
        else:
            continue
        try:
            p.unlink()
            logger.info("Removed metadata for %s (%s)", rec_id, stale_reason)
        except OSError as e:
            logger.warning("Could not remove orphan metadata %s: %s", p.name, e)


def _new_rec_id() -> str:
    return secrets.token_hex(8)


def _load_or_create_admin_token(token_path: Path) -> str:
    try:
        if token_path.exists():
            token = token_path.read_text().strip()
            if token:
                return token
        token = secrets.token_urlsafe(24)
        token_path.parent.mkdir(parents=True, exist_ok=True)
        token_path.write_text(token)
    except OSError as e:
        logger.exception("FATAL: cannot read or create admin token file %s", token_path)
        raise RuntimeError(f"admin token IO failed: {e}") from e
    try:
        token_path.chmod(0o600)
    except OSError as e:
        # Token file is potentially world-readable; warn loudly so an
        # operator noticing odd permissions has an audit trail.
        logger.warning("Could not chmod admin token file %s to 0600: %s", token_path, e)
    return token


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------


class _State:
    """Per-server state shared by handler instances via a class attr."""

    def __init__(
        self,
        rec_dir: Path,
        admin_token: str,
        max_bytes: int,
        public_origin_hint: str | None,
    ) -> None:
        self.rec_dir = rec_dir
        self.admin_token = admin_token
        self.max_bytes = max_bytes
        # Origin (scheme+host) used only when the server logs the
        # listing URL at startup, so the operator can paste it into
        # a browser. Inside the listing page itself, all URLs are
        # relative.
        self.public_origin_hint = public_origin_hint or ""


class _Handler(BaseHTTPRequestHandler):
    state: _State  # set before serving

    server_version = "openhost-jitsi-recordings/1"

    # Silence the default per-request stderr logging; we log
    # explicitly for the requests we care about.
    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002, D401
        return

    # -- helpers ------------------------------------------------------------

    def _json(self, status: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _error(self, status: int, message: str) -> None:
        self._json(status, {"error": message})

    def _read_json_body(self, max_bytes: int = 64 * 1024) -> dict[str, Any] | None:
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            return None
        if length <= 0 or length > max_bytes:
            return None
        try:
            data = self.rfile.read(length)
        except OSError:
            return None
        try:
            payload = json.loads(data.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            return None
        return payload if isinstance(payload, dict) else None

    # -- routing ------------------------------------------------------------

    def do_GET(self) -> None:  # noqa: N802 (BaseHTTPRequestHandler API)
        url = urlparse(self.path)
        path = url.path

        if path == "/api/recordings/health":
            return self._json(200, {"ok": True})

        # Admin endpoints under /_recordings/<token>/...
        admin_match = re.match(r"^/_recordings/([^/]+)/?(.*)$", path)
        if admin_match and secrets.compare_digest(admin_match.group(1), self.state.admin_token):
            tail = admin_match.group(2)
            return self._handle_admin_get(tail, parse_qs(url.query))

        return self._error(HTTPStatus.NOT_FOUND, "not found")

    def do_POST(self) -> None:  # noqa: N802
        url = urlparse(self.path)
        path = url.path

        if path == "/api/recordings/init":
            return self._handle_init()

        chunk_match = re.match(r"^/api/recordings/([a-f0-9]{16})/chunk$", path)
        if chunk_match:
            return self._handle_chunk(chunk_match.group(1))

        finalize_match = re.match(r"^/api/recordings/([a-f0-9]{16})/finalize$", path)
        if finalize_match:
            return self._handle_finalize(finalize_match.group(1))

        return self._error(HTTPStatus.NOT_FOUND, "not found")

    def do_DELETE(self) -> None:  # noqa: N802
        url = urlparse(self.path)
        path = url.path
        admin_match = re.match(r"^/_recordings/([^/]+)/recording/([a-f0-9]{16})$", path)
        if admin_match and secrets.compare_digest(admin_match.group(1), self.state.admin_token):
            rec_id = admin_match.group(2)
            return self._handle_admin_delete(rec_id)
        return self._error(HTTPStatus.NOT_FOUND, "not found")

    # -- handlers: anonymous upload path -----------------------------------

    def _handle_init(self) -> None:
        body = self._read_json_body() or {}
        room = str(body.get("room", "")).strip()
        started_by = str(body.get("started_by", "")).strip()[:64] or "anonymous"
        if not ROOM_RE.fullmatch(room):
            return self._error(HTTPStatus.BAD_REQUEST, "invalid room")

        rec_id = _new_rec_id()
        meta = {
            "id": rec_id,
            "room": room,
            "started_by": started_by,
            "started_at": _now_iso(),
            "finished_at": None,
            "size_bytes": 0,
            "finalized": False,
        }
        with _state_lock:
            try:
                _tmp_path(self.state.rec_dir, rec_id).touch()
                _write_meta(self.state.rec_dir, rec_id, meta)
            except OSError as e:
                logger.exception("init failed for %s", rec_id)
                return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, f"could not initialize recording: {e}")
        logger.info("init recording %s in room %r by %r", rec_id, room, started_by)
        return self._json(200, {"id": rec_id, "chunk_size": DEFAULT_CHUNK_SIZE})

    def _handle_chunk(self, rec_id: str) -> None:
        if not ID_RE.fullmatch(rec_id):
            return self._error(HTTPStatus.BAD_REQUEST, "invalid id")
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            return self._error(HTTPStatus.BAD_REQUEST, "invalid Content-Length")
        if length <= 0:
            return self._error(HTTPStatus.BAD_REQUEST, "empty chunk")
        if length > MAX_CHUNK_BYTES:
            return self._error(HTTPStatus.REQUEST_ENTITY_TOO_LARGE, f"chunk too large (max {MAX_CHUNK_BYTES})")

        with _state_lock:
            meta = _read_meta(self.state.rec_dir, rec_id)
            if meta is None:
                return self._error(HTTPStatus.NOT_FOUND, "no such recording")
            if meta.get("finalized"):
                return self._error(HTTPStatus.CONFLICT, "already finalized")
            tmp = _tmp_path(self.state.rec_dir, rec_id)
            if not tmp.exists():
                return self._error(HTTPStatus.GONE, "recording gone")
            # Quick fail-fast capacity check: reject if even our most
            # aggressive eviction couldn't fit the chunk. We don't
            # ACT on the eviction yet — that happens only after we've
            # actually received bytes — but if there's no possible way
            # for the chunk to land, the client deserves an early 507.
            #
            # NOTE: this is an over-approximation. ``_disk_usage`` counts
            # every file in the recordings dir (json, tmp, webm),
            # while ``size_bytes`` only tracks .webm size; a finalized
            # recording's metadata file (~150 bytes) effectively
            # raises the floor by that much. The miscounting only
            # over-rejects, never under-rejects, so it's a soft
            # tightening of the cap rather than a leak.
            current_usage = _disk_usage(self.state.rec_dir)
            evictable = sum(
                int(m.get("size_bytes", 0))
                for m in _list_meta(self.state.rec_dir)
                if m.get("finalized")
            )
            if (current_usage - evictable) + length > self.state.max_bytes:
                return self._error(
                    HTTPStatus.INSUFFICIENT_STORAGE,
                    "disk quota exceeded; even evicting all finalized recordings wouldn't fit",
                )

        # Take the per-recording lock so two POSTs for the same
        # rec_id don't interleave bytes in the tmp file. We hold it
        # across the streaming + metadata-update pair; concurrent
        # chunks for DIFFERENT recordings still proceed in parallel.
        rec_lock = _chunk_lock_for(rec_id)
        with rec_lock:
            return self._stream_chunk_locked(rec_id, length, tmp)

    def _stream_chunk_locked(self, rec_id: str, length: int, tmp: Path) -> None:
        # Stream the body to disk in fixed-size reads outside the global lock.
        # Only AFTER we have actual bytes do we trigger eviction —
        # otherwise an attacker could claim a large Content-Length,
        # disconnect, and force eviction of every finalized recording
        # while contributing zero bytes themselves.
        #
        # If the write fails partway, truncate back to the pre-chunk
        # size so that a client retry doesn't append duplicate bytes
        # on top of a partial write (would corrupt the WebM).
        try:
            pre_chunk_size = tmp.stat().st_size
        except OSError:
            # Concurrent admin DELETE removed tmp between the lock
            # release and here; the upload is dead.
            return self._error(HTTPStatus.GONE, "recording was deleted before chunk could be written")
        try:
            written = self._stream_to_file(tmp, length)
        except OSError as e:
            logger.exception("write failed for %s; rolling back tmp to %d bytes", rec_id, pre_chunk_size)
            # Open in r+b (not ab) so a concurrent admin DELETE that
            # removed the tmp file produces FileNotFoundError instead
            # of recreating an empty file.
            try:
                with tmp.open("r+b") as fh:
                    fh.truncate(pre_chunk_size)
            except FileNotFoundError:
                logger.info("rollback skipped: tmp for %s was deleted concurrently", rec_id)
            except OSError as e2:
                logger.warning("rollback truncate failed for %s: %s; tmp may be corrupted", rec_id, e2)
            return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, f"write failed: {e}")

        with _state_lock:
            meta = _read_meta(self.state.rec_dir, rec_id)
            if meta is None:
                # An admin DELETE finished while we were streaming.
                # Don't recreate metadata for a recording that was
                # explicitly removed; just drop the bytes we wrote.
                try:
                    _tmp_path(self.state.rec_dir, rec_id).unlink(missing_ok=True)
                except OSError:
                    pass
                return self._error(HTTPStatus.NOT_FOUND, "recording was deleted mid-upload")
            try:
                meta["size_bytes"] = int(meta.get("size_bytes", 0)) + written
                _write_meta(self.state.rec_dir, rec_id, meta)
            except OSError as e:
                logger.exception("metadata write failed after chunk for %s", rec_id)
                return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, f"metadata write failed: {e}")
            # Now that we've actually written bytes, evict if needed
            # to bring total usage back under the cap.
            _evict_until_under_cap(self.state.rec_dir, 0, self.state.max_bytes)
        return self._json(200, {"ok": True, "received": written, "total": meta["size_bytes"]})

    def _handle_finalize(self, rec_id: str) -> None:
        if not ID_RE.fullmatch(rec_id):
            return self._error(HTTPStatus.BAD_REQUEST, "invalid id")
        with _state_lock:
            meta = _read_meta(self.state.rec_dir, rec_id)
            if meta is None:
                return self._error(HTTPStatus.NOT_FOUND, "no such recording")
            tmp = _tmp_path(self.state.rec_dir, rec_id)
            final = _final_path(self.state.rec_dir, rec_id)
            if meta.get("finalized"):
                if final.exists():
                    return self._json(200, {"ok": True, "already_finalized": True})
                return self._error(HTTPStatus.GONE, "recording deleted after finalize")
            # Repair-on-retry: a previous finalize may have done the
            # rename, then crashed before persisting `finalized=True`.
            # Detect that and proceed to repair the metadata only.
            if not tmp.exists() and final.exists():
                logger.info("finalize-retry: tmp gone, final present for %s; repairing meta", rec_id)
            elif not tmp.exists():
                return self._error(HTTPStatus.GONE, "recording gone")
            else:
                try:
                    os.replace(tmp, final)
                except OSError as e:
                    logger.exception("rename failed for %s", rec_id)
                    return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, f"rename failed: {e}")
            # Bytes are committed (either we just renamed or a prior
            # finalize did). Stamp meta. If the metadata write fails,
            # the next retry hits the repair branch above and tries
            # again.
            try:
                size = final.stat().st_size
            except OSError as e:
                logger.warning("stat failed after rename for %s: %s; using tracked size", rec_id, e)
                size = int(meta.get("size_bytes", 0))
            meta["finished_at"] = _now_iso()
            meta["size_bytes"] = size
            meta["finalized"] = True
            try:
                _write_meta(self.state.rec_dir, rec_id, meta)
            except OSError as e:
                logger.exception("metadata write failed in finalize for %s", rec_id)
                return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, f"metadata write failed: {e}")
        logger.info("finalized recording %s (%d bytes)", rec_id, meta["size_bytes"])
        # No more chunks will arrive for this recording; drop its lock.
        _drop_chunk_lock(rec_id)
        return self._json(200, {"ok": True})

    def _stream_to_file(self, path: Path, length: int) -> int:
        """Copy ``length`` bytes from rfile to the end of ``path``."""
        copied = 0
        # Open in append mode; multiple chunks accumulate.
        with path.open("ab") as out:
            remaining = length
            while remaining > 0:
                buf = self.rfile.read(min(64 * 1024, remaining))
                if not buf:
                    raise OSError("client disconnected mid-chunk")
                out.write(buf)
                copied += len(buf)
                remaining -= len(buf)
        return copied

    # -- handlers: admin path ----------------------------------------------

    def _handle_admin_get(self, tail: str, query: dict[str, list[str]]) -> None:
        # /<token>/        → HTML listing (do_GET's regex consumes
        # the trailing slash before the tail capture, so tail is "")
        # /<token>/recording/<id> → file download
        if tail == "":
            return self._render_listing()
        m = re.match(r"^recording/([a-f0-9]{16})$", tail)
        if m:
            return self._serve_recording(m.group(1))
        return self._error(HTTPStatus.NOT_FOUND, "not found")

    def _handle_admin_delete(self, rec_id: str) -> None:
        errors: list[str] = []
        # Drop any per-recording chunk lock so a future re-init with
        # the same id (extremely unlikely; ids are 64-bit random) or
        # a stuck thread doesn't keep a dead reference around.
        _drop_chunk_lock(rec_id)
        with _state_lock:
            meta = _read_meta(self.state.rec_dir, rec_id)
            if meta is None:
                return self._error(HTTPStatus.NOT_FOUND, "no such recording")
            for p in (
                _final_path(self.state.rec_dir, rec_id),
                _tmp_path(self.state.rec_dir, rec_id),
                _meta_path(self.state.rec_dir, rec_id),
            ):
                try:
                    p.unlink(missing_ok=True)
                except OSError as e:
                    logger.warning("delete %s: %s", p, e)
                    errors.append(f"{p.name}: {e}")
        if errors:
            # Some files couldn't be removed; surface the failure so
            # the admin UI doesn't show a misleading green tick.
            return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, "; ".join(errors))
        return self._json(200, {"ok": True})

    def _serve_recording(self, rec_id: str) -> None:
        meta = _read_meta(self.state.rec_dir, rec_id)
        if meta is None or not meta.get("finalized"):
            return self._error(HTTPStatus.NOT_FOUND, "not found")
        path = _final_path(self.state.rec_dir, rec_id)
        # Open before reading the size so the size we send in the
        # Content-Length header matches the bytes we'll actually
        # stream. A concurrent DELETE between stat and open would
        # otherwise either truncate the response or surface as an
        # unhandled OSError after headers are already sent.
        try:
            fh = path.open("rb")
        except FileNotFoundError:
            return self._error(HTTPStatus.NOT_FOUND, "not found")
        except OSError as e:
            logger.exception("could not open %s for serving", rec_id)
            return self._error(HTTPStatus.INTERNAL_SERVER_ERROR, f"open failed: {e}")

        try:
            size = os.fstat(fh.fileno()).st_size
            room = meta.get("room", "recording")
            safe_room = re.sub(r"[^A-Za-z0-9._-]", "_", room)
            ts = (meta.get("started_at", "") or "").replace(":", "-")
            download_name = f"{safe_room}_{ts}.webm"

            self.send_response(200)
            self.send_header("Content-Type", "video/webm")
            self.send_header("Content-Length", str(size))
            self.send_header("Content-Disposition", f'attachment; filename="{download_name}"')
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            try:
                shutil.copyfileobj(fh, self.wfile, length=64 * 1024)
            except (BrokenPipeError, ConnectionResetError):
                # Client gave up mid-download; nothing actionable.
                pass
        finally:
            fh.close()

    def _render_listing(self) -> None:
        recordings = _list_meta(self.state.rec_dir)
        total_bytes = sum(int(m.get("size_bytes", 0)) for m in recordings if m.get("finalized"))
        rows = []
        for m in recordings:
            if not m.get("finalized"):
                state = "uploading"
                action = ""
            else:
                state = "ready"
                action = (
                    f'<a href="recording/{m["id"]}">download</a> '
                    f'<a href="#" onclick="del(\'{m["id"]}\');return false">delete</a>'
                )
            size_mb = f'{m.get("size_bytes", 0) / 1_000_000:.1f}'
            rows.append(
                "<tr>"
                f'<td>{html.escape(m.get("room", ""))}</td>'
                f'<td>{html.escape(m.get("started_at", ""))}</td>'
                f'<td>{html.escape(m.get("started_by", ""))}</td>'
                f'<td style="text-align:right">{size_mb} MB</td>'
                f"<td>{state}</td>"
                f"<td>{action}</td>"
                "</tr>"
            )
        body = LISTING_HTML.format(
            rows="\n".join(rows) or '<tr><td colspan="6" style="text-align:center;color:#888">No recordings yet.</td></tr>',
            total_mb=f"{total_bytes / 1_000_000:.1f}",
            cap_mb=f"{self.state.max_bytes / 1_000_000:.0f}",
            count=len(recordings),
        )
        encoded = body.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(encoded)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(encoded)


LISTING_HTML = """<!doctype html>
<html><head>
<meta charset="utf-8">
<title>Jitsi Recordings</title>
<style>
body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 1100px; margin: 2em auto; padding: 0 1em; color: #222; }}
h1 {{ margin-bottom: 0.2em; }}
.summary {{ color: #666; margin-bottom: 1.5em; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border-bottom: 1px solid #ddd; padding: 0.5em 0.6em; text-align: left; }}
th {{ background: #f5f5f5; font-weight: 600; font-size: 0.9em; }}
a {{ color: #0366d6; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
</style>
</head><body>
<h1>Jitsi Recordings</h1>
<div class="summary">{count} recording(s), {total_mb} MB used of {cap_mb} MB cap.</div>
<table>
<thead><tr>
<th>Room</th><th>Started</th><th>Started by</th><th>Size</th><th>State</th><th></th>
</tr></thead>
<tbody>
{rows}
</tbody></table>
<script>
async function del(id) {{
  if (!confirm('Delete this recording permanently?')) return;
  const r = await fetch('recording/' + id, {{method: 'DELETE'}});
  if (r.ok) location.reload();
  else alert('Delete failed: HTTP ' + r.status);
}}
</script>
</body></html>
"""


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--rec-dir", required=True, type=Path)
    p.add_argument("--admin-token-file", required=True, type=Path)
    p.add_argument("--port", type=int, default=5060)
    p.add_argument("--bind", default="127.0.0.1")
    p.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES)
    p.add_argument("--public-origin-hint", default="")
    return p.parse_args(argv)


def run(args: argparse.Namespace) -> None:
    args.rec_dir.mkdir(parents=True, exist_ok=True)
    _sweep_orphans(args.rec_dir)
    admin_token = _load_or_create_admin_token(args.admin_token_file)
    state = _State(
        rec_dir=args.rec_dir,
        admin_token=admin_token,
        max_bytes=args.max_bytes,
        public_origin_hint=args.public_origin_hint,
    )
    _Handler.state = state
    server = ThreadingHTTPServer((args.bind, args.port), _Handler)
    listing_url = f"/_recordings/{admin_token}/"
    if state.public_origin_hint:
        listing_url = f"{state.public_origin_hint.rstrip('/')}{listing_url}"
    logger.info("listening on %s:%s", args.bind, args.port)
    logger.info("recordings listing URL (keep secret): %s", listing_url)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s")
    args = parse_args(argv)
    run(args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
